import {
  INITIAL_DEVOPS_X_POSITION,
  INITIAL_DEVOPS_Y_POSITION,
  INITIAL_PROGRAM_X_POSITION,
  INITIAL_PROGRAM_Y_POSITION,
} from './constants';

export const DEVOPS_TITLE_ANIMATION = {
  y: INITIAL_DEVOPS_Y_POSITION,
  x: INITIAL_DEVOPS_X_POSITION,
};

export const PROGRAM_TITLE_ANIMATION = {
  y: INITIAL_PROGRAM_Y_POSITION,
  x: INITIAL_PROGRAM_X_POSITION,
};
