export const INITIAL_DEVOPS_Y_POSITION = 150;
export const INITIAL_DEVOPS_X_POSITION = 150;
export const INITIAL_DEVOPS_ROTATE_POSITION = 40;
export const INITIAL_PROGRAM_Y_POSITION = 350;
export const INITIAL_PROGRAM_ROTATE_POSITION = 40;
